version: '3.8'

services:
  mariadb:
    image: mariadb:10.5.28
    container_name: mariadb_10_5_28
    environment:
      MYSQL_ROOT_PASSWORD: database
      MYSQL_DATABASE: database
      MYSQL_USER: database
      MYSQL_PASSWORD: database
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: